# 3.20内容

## 手写promise

### 函数版本
```JS
/* 
函数版本
自定义Promise函数模块
 */
// es5 自定义模块：IFFE

(function(window) {
    const PENDING = 'pending';
    const RESOLVED = 'resolved';
    const REJECTED = 'rejected';
    /*
    Promise构造函数
    传入excutor：执行器函数(同步)
     */
   function Promise(excutor) {
       let self = this; // 将当前promise对象保存起来
       self.status = PENDING; // 给promise对象指定初始状态
       self.data = undefined; // 给promised对象指定一个用于存储结果数据的属性
       self.callbacks = []; //存储待执行的回调函数, {onResolved(){}, onRejected(){}}
       function resolve(value) {
           // 如果当前状态不是pending,直接结束，因为状态只能改变一次
           if (self.status !== PENDING) {
               return;
           }
           // 将状态改为resolved
           self.status = RESOLVED;
           // 保存value数据
           self.data = value;
           // 如果有待执行的callback函数，立即异步执行回调
           if (self.callbacks.length) {
               setTimeout(() => { // 放到事件队列中执行所有成功的回调
                   self.callbacks.forEach(callbacksObj => {
                    callbacksObj.onResolved(value);
                })
               })
           }
       }
       function reject(reason) {
           // 如果当前状态不是pending,直接结束，因为状态只能改变一次
           if (self.status !== PENDING) {
               return;
           }
           // 将状态改为rejected
           self.status = REJECTED;
           // 保存reason数据
           self.data = reason;
           // 如果有待执行的callback函数，立即异步执行回调
           if(self.callbacks.length) { // 放到事件队列中执行所有失败的回调
               setTimeout(() => {
                   self.callbacks.forEach(callbacksObj => {
                       callbacksObj.onRejected(reason);
                   })
               })
           }
       }
       // 立即同步执行excutor
       try {
           excutor(resolve,reject);
       } catch(error) { // 如果执行器抛出异常，promise对象变为rejected状态
           reject(error);
       }
   } 
   /*
   Promise原型对象的then()
   指定成功和失败的回调函数
   返回一个新的promise对象
   返回的promise的结果由onResolved/onRejected的执行结果决定
    */
   Promise.prototype.then = function(onResolved, onRejected) {
       onResolved = typeof onResolved === 'function' ? onResolved : value => value // 向后传递成功点value
       // 指定默认的失败的回调，实现异常传透关键点
       onRejected = typeof onRejected === 'function' ? onRejected : reason => {throw reason} // 向后传递失败的reason
       const self = this;
       //返回一个新的promise对象
       return new Promise((resolve,reject) => {
           /*
           调用指定回调函数处理
            */
           function handle(callback) {
               /*
                1、如果抛出异常，return的promise就会失败，reason就是error
                2、如果回调函数返回非promise,那return的promise就会成功，value就是返回的值
                3、如果回调函数返回是promise,return的promise结果就是这个promise的结果
                */
               try {
                    const result = callback(self.data);
                    if (result instanceof Promise) {
                        result.then(
                            value => { // 当result成功时，让return的promise也成功
                                resolve(value);
                            },
                            reason => {// 当result失败时，让return的promise也失败
                                reject(reason);
                            }
                        )
                        // 更高效的写法
                        // result.then(resolve,reject);
                    } else {
                        resolve(result);
                    }
                } catch(error) {
                    reject(error);
                }
           }
           // 当前状态是pending状态，需要保存起来
           // 等待状态变为resolved或rejected，执行相应回调
           // 还要改变新的promise的状态
            if (self.status === PENDING) {
                self.callbacks.push({
                    onResolved(value){
                        handle(onResolved);
                    },
                    onRejected(reason) {
                        handle(onRejected);
                    }
                });
            } else if (self.status === RESOLVED) { // 状态若是为resolved，那么执行onResolved函数
                setTimeout(() => { // 回调函数要异步执行
                   handle(onResolved);
                })
            } else { // 'rejected'
                setTimeout(() => { // 回调函数要异步执行
                   handle(onRejected);
                })
            }
       })
   }
   /*
   Promise原型对象的catch()
   指定失败的回调函数
   返回一个新的promise
    */
   Promise.prototype.catch = function(onRejected) {
       console.log('catach');
        return this.then(undefined,onRejected);
   }
   /*
   Promise函数对象方法resolve
   返回一个指定结果的成功的promise
    */
   Promise.resolve = function(value) {
       // 返回一个成功/失败promise
       return new Promise((resolve, reject) => {
           // value是promise
           if (value instanceof Promise) { // i使用value的结果作为当前promise的结果
               value.then(resolve,reject);
           } else { // value不是promise,promise变为成功，数据是value
             resolve(value);
           }
       })
   }
   /*
   Promise函数对象方法reject
   返回一个指定reason的失败的promise
    */
   Promise.reject = function(reason) {
       // 返回一个失败的promise
       return new Promise((resolve,reject) => {
           reject(reason);
       })
   }
   /*
   Promise函数对象方法all
   返回一个promise,只有当所有promise都成功时才成功，
   否则只要有一个失败的就失败
    */
   Promise.all = function(promises) {
       const values = new Array(promises.length); // 用来保存所有成功value的数组
       let resolvedcount = 0;// 用来保存成功promise的数量
       return new Promise((resolve, reject) => {
           // 遍历promises获取每个promise的结果
           promises.forEach((promise,index) => {
               Promise.resolve(promise).then(
                   value => { // 只能代表当前promise成功了，将成功的value保存到values
                       values[index] = value;
                       resolvedcount ++ ; // 成功的数量加1
                       //如果全部成功了，将return的promise改为成功
                       if (resolvedcount === promises.length) {
                           resolve(values);
                       }
                   },
                   reason => { // 只要有一个失败，return的promise就失败
                        reject(reason);
                   }
               )
           })
       })
   }
   /*
   Promise函数对象方法race
   返回一个promise，其结果由第一个完成的promise决定
    */
   Promise.race = function(promises) {
       return new Promise((resolve, reject) => {
           // 遍历promises获取每个promise的结果,看谁最先完成
           promises.forEach((promise,index) => { // Promise.resolve(promise)兼容传入的数组中传入普通值的情况
                Promise.resolve(promise).then(
                    value => { //一旦有成功了，将return的promise变为成功
                        resolve(value);
                    },
                    reason => { // 一旦有失败了，将return的promise变为失败
                        reject(reason);
                    }
                )
           })
       })
   }
   
   /*
   返回一个promise对象，它在指定的时间后才确定结果
    */
   Promise.resolveDelay = function(value,time) {
       // 返回一个成功/失败promise
       return new Promise((resolve, reject) => {
           setTimeout(() => {
               // value是promise
                if (value instanceof Promise) { // i使用value的结果作为当前promise的结果
                    value.then(resolve,reject);
                } else { // value不是promise,promise变为成功，数据是value
                    resolve(value);
                }
           },time)
       })
   }
   /*
   返回一个promise对象，它在指定的时间后才确定结果
    */
   Promise.rejectDelay = function(reason,time) {
        // 返回一个失败的promise
        return new Promise((resolve,reject) => {
            setTimeout(() => {
                reject(reason);
            },time)
        })
    }
   // 向外暴露Promise函数
   window.Promise = Promise;
})(window)

```
### 类版本

```JS
/* 
类版本
自定义Promise函数模块
 */
// es5 自定义模块：IFFE

(function(window) {
    const PENDING = 'pending';
    const RESOLVED = 'resolved';
    const REJECTED = 'rejected';
    
    class Promise {
        constructor(excutor) {
            let self = this; // 将当前promise对象保存起来
            self.status = PENDING; // 给promise对象指定初始状态
            self.data = undefined; // 给promised对象指定一个用于存储结果数据的属性
            self.callbacks = []; //存储待执行的回调函数, {onResolved(){}, onRejected(){}}
            function resolve(value) {
                // 如果当前状态不是pending,直接结束，因为状态只能改变一次
                if (self.status !== PENDING) {
                    return;
                }
                // 将状态改为resolved
                self.status = RESOLVED;
                // 保存value数据
                self.data = value;
                // 如果有待执行的callback函数，立即异步执行回调
                if (self.callbacks.length) {
                    setTimeout(() => { // 放到事件队列中执行所有成功的回调
                        self.callbacks.forEach(callbacksObj => {
                            callbacksObj.onResolved(value);
                        })
                    })
                }
            }
            function reject(reason) {
                // 如果当前状态不是pending,直接结束，因为状态只能改变一次
                if (self.status !== PENDING) {
                    return;
                }
                // 将状态改为rejected
                self.status = REJECTED;
                // 保存reason数据
                self.data = reason;
                // 如果有待执行的callback函数，立即异步执行回调
                if(self.callbacks.length) { // 放到事件队列中执行所有失败的回调
                    setTimeout(() => {
                        self.callbacks.forEach(callbacksObj => {
                            callbacksObj.onRejected(reason);
                        })
                    })
                }
            }
            // 立即同步执行excutor
            try {
                excutor(resolve,reject);
            } catch(error) { // 如果执行器抛出异常，promise对象变为rejected状态
                reject(error);
            }
        }
        then (onResolved, onRejected) {
            onResolved = typeof onResolved === 'function' ? onResolved : value => value // 向后传递成功点value
            // 指定默认的失败的回调，实现异常传透关键点
            onRejected = typeof onRejected === 'function' ? onRejected : reason => {throw reason} // 向后传递失败的reason
            const self = this;
            //返回一个新的promise对象
            return new Promise((resolve,reject) => {
                /*
                调用指定回调函数处理
                    */
                function handle(callback) {
                    /*
                        1、如果抛出异常，return的promise就会失败，reason就是error
                        2、如果回调函数返回非promise,那return的promise就会成功，value就是返回的值
                        3、如果回调函数返回是promise,return的promise结果就是这个promise的结果
                        */
                    try {
                            const result = callback(self.data);
                            if (result instanceof Promise) {
                                result.then(
                                    value => { // 当result成功时，让return的promise也成功
                                        resolve(value);
                                    },
                                    reason => {// 当result失败时，让return的promise也失败
                                        reject(reason);
                                    }
                                )
                                // 更高效的写法
                                // result.then(resolve,reject);
                            } else {
                                resolve(result);
                            }
                        } catch(error) {
                            reject(error);
                        }
                }
                // 当前状态是pending状态，需要保存起来
                // 等待状态变为resolved或rejected，执行相应回调
                // 还要改变新的promise的状态
                    if (self.status === PENDING) {
                        self.callbacks.push({
                            onResolved(value){
                                handle(onResolved);
                            },
                            onRejected(reason) {
                                handle(onRejected);
                            }
                        });
                    } else if (self.status === RESOLVED) { // 状态若是为resolved，那么执行onResolved函数
                        setTimeout(() => { // 回调函数要异步执行
                        handle(onResolved);
                        })
                    } else { // 'rejected'
                        setTimeout(() => { // 回调函数要异步执行
                        handle(onRejected);
                        })
                    }
            })
        }
        catch (onRejected) {
            return this.then(undefined,onRejected);
        }
       static resolve (value) {
            // 返回一个成功/失败promise
            return new Promise((resolve, reject) => {
                // value是promise
                if (value instanceof Promise) { // i使用value的结果作为当前promise的结果
                    value.then(resolve,reject);
                } else { // value不是promise,promise变为成功，数据是value
                    resolve(value);
                }
            })
        }
       static reject (reason) {
            // 返回一个失败的promise
            return new Promise((resolve,reject) => {
                reject(reason);
            })
        }
        static all(promises) {
            const values = new Array(promises.length); // 用来保存所有成功value的数组
            let resolvedcount = 0;// 用来保存成功promise的数量
            return new Promise((resolve, reject) => {
                // 遍历promises获取每个promise的结果
                promises.forEach((promise,index) => {
                    Promise.resolve(promise).then(
                        value => { // 只能代表当前promise成功了，将成功的value保存到values
                            values[index] = value;
                            resolvedcount ++ ; // 成功的数量加1
                            //如果全部成功了，将return的promise改为成功
                            if (resolvedcount === promises.length) {
                                resolve(values);
                            }
                        },
                        reason => { // 只要有一个失败，return的promise就失败
                                reject(reason);
                        }
                    )
                })
            })
        }
        static race (promises) {
            return new Promise((resolve, reject) => {
                // 遍历promises获取每个promise的结果,看谁最先完成
                promises.forEach((promise,index) => { // Promise.resolve(promise)兼容传入的数组中传入普通值的情况
                        Promise.resolve(promise).then(
                            value => { //一旦有成功了，将return的promise变为成功
                                resolve(value);
                            },
                            reason => { // 一旦有失败了，将return的promise变为失败
                                reject(reason);
                            }
                        )
                })
            })
        }
        static resolveDelay (value,time) {
            // 返回一个成功/失败promise
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    // value是promise
                        if (value instanceof Promise) { // i使用value的结果作为当前promise的结果
                            value.then(resolve,reject);
                        } else { // value不是promise,promise变为成功，数据是value
                            resolve(value);
                        }
                },time)
            })
        }
        static rejectDelay (reason,time) {
            // 返回一个失败的promise
            return new Promise((resolve,reject) => {
                setTimeout(() => {
                    reject(reason);
                },time)
            })
        }
    }
   window.Promise = Promise;
})(window)

```

